apiVersion: v1
kind: Pod
metadata:
  name: sample-eks
  labels:
    Group : Krishna
    Created_by : Yogesh
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
